sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t aromeroj/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true aromeroj/docker-react npm run test